"""Listing of special values encoded in the database for MCDI information.

@author: Sam Pottinger
@license: GNU GPL v2
"""

NO_DATA = -100
UNKNOWN = -200
POSSIBLY_WRONGLY_REC = -300
EMERGENCY_REC = -400
IMPLIED_FALSE = -500
EXPLICIT_TRUE = 1
EXPLICIT_FALSE = 2
EXPLICIT_NONE = -600
EXPLICIT_NA = -700
EXPLICIT_OTHER = -800
NO_EXTRA_CATEGORIES = -900
EXTRA_CATEGORIES = -1000
ELEVEN_PRESUMED_TRUE = -3000
TRUE_VALS = [EXPLICIT_TRUE, ELEVEN_PRESUMED_TRUE]

MALE = -2001
FEMALE = -2002
OTHER_GENDER = -2003
